### ISSUE TITLE
[Bug] Physical Analog/DPad not working 

### ISSUE THREAD

**Issue by Gymcap** [Swordfish90/Lemuroid#136]
I'm using an 8BitDo SN30 Pro+ and neither the Analog sticks nor the DPad seem to be recognized or give inputs. Everything else seemingly works, but I can’t do much without a DPad at least. :p

Is there any fix for this at the moment?

**Comment by Swordfish90** [comment]
Hi @Gymcap . Thanks for reporting this. Could you provide a little bit more details? On which device are you testing it, which Android version?

**Comment by aIgarcia** [comment]
I'm having the same problem. I just installed this on my Android TV, Lemuroid recognizes my SN30 Pro in any of the 4 modes in both wireless and wired, however I'm unable to play. I think for some reason Lemuroid thinks my controller is player two instead of one: In streets of rage 2 for the Genesis it only highlights player two and I can choose the character, same for Playstation. I can't do anything on SNES and with Nintendo it works but the layout is weird.

I think everything with the emulator itself is great but having an option to set my own bindings would fix all of this. The best approach would definetely be an autodetect by keypress instead of choosing which key is which from a menu, even more when the xbox and nintendo layouts don't match.

**Comment by Swordfish90** [comment]
The latest version 1.9.0 should fix gamepads detected as player 2 on some TV boxes. Please feel free to let me know if now everything works correctly.
