### ISSUE TITLE
Add support for SEGA CD

### ISSUE THREAD

**Issue by Dougzen** [Swordfish90/Lemuroid#234]
Hello,

I tried all the recommendations here about the subject.

But the system can't read any bin or iso file that is a SEGA CD game.

**Comment by Dougzen** [comment]
Update:

Picodrive is a APK that can run Sega CD games.
Will be interesting using this how one core.

**Comment by Swordfish90** [comment]
Hi @Dougzen . SEGA CD games are currently not supported. This is not a core issue, as they are already available in Genesis Plus GX: https://docs.libretro.com/library/genesis_plus_gx/ .

The problem is that Lemuroid needs to figure out that the iso/cue/bin file it found is actually a SEGA CD game (as opposed to PSX or PSP games which have the same format).

**Comment by Squidward22** [comment]
I MADE ISSUE #467
