### ISSUE TITLE
How does the Google Drive sync work?

### ISSUE THREAD

**Issue by eriqjaffe** [Swordfish90/Lemuroid#296]
I see that this was implemented in 1.9.0 (I'm on 1.11.1) but I don't see anything in the app to configure or enable it.

**Comment by Swordfish90** [comment]
Hi @eriqjaffe . You need to go into Settings -> Cloud Saves -> Configure Google Drive . You can sync both in-game saves and states by choosing the appropriate options in that menu.

**Comment by eriqjaffe** [comment]
I don't save "Cloud Saves" in the settings?  This is what I have, unless there's somewhere else I should be looking:

`ROMs
	Directory
	Rescan
	
GENERAL
	Display filter
	Autosave state
	
INPUT
	Vibrate on touch
	Gamepad settings
	Tilt sensor sensitivyt
	
ADVANCED
	Change cores
	BIOS
	Factory reset`

**Comment by Swordfish90** [comment]
I see. I guess you downloaded the open-source version here from GitHub.

Google Drive Sync is only supported on the Google Play version (because it has to use proprietary libraries by Google), so you need to install it from Google Play: https://play.google.com/store/apps/details?id=com.swordfish.lemuroid

**Comment by eriqjaffe** [comment]
Got it, thanks!

**Comment by eriqjaffe** [comment]
Finally had some time to try and set this up only to discover that the files in Google Drive are hidden so I can't sync them with RetroArch on my PC - is there any way to work around that?

**Comment by hhromic** [comment]
> Finally had some time to try and set this up only to discover that the files in Google Drive are hidden so I can't sync them with RetroArch on my PC - is there any way to work around that?

Sadly I just stumbled upon the same "gotcha". I'm trying to sync saves between my phone, my Android TV box and my laptop computer. The first two are fine because they are both Android devices using the same application (Lemuroid) but there is no way to access the save data from a non-Android device because they are in the application "private data" area.

Unfortunately I don't think there is an easy solution to this because Google does not seem to support an API to be used outside of the application to access its private data (very understandable). A possible solution would be for Lemuroid to store/read files to/from Google Drive as regular files instead of application private data. However this probably means a lot of work and surely means breaking up all existing setups :(
