### ISSUE TITLE
Core options

### ISSUE THREAD

**Issue by Amnesia1000** [Swordfish90/Lemuroid#38]
Enabling core options is essential. An example of this is for example in GBA, to play Boktai, it is necessary to modify the sunlight meter, or to be able to tell you what time and day it is at the core. In addition to having greater control of the core and how it works.

**Comment by Swordfish90** [comment]
Hi, this landed with fccf75044. Only a subset of the core options are exposed because some are meaningful only on some platforms or might break the emulator (such as setting mouse pointer in desmume) and I want to keep it as simple as possible. If you see anything mandatory missing feel free to tell me, adding them is just one line of code.
