### ISSUE TITLE
Implement CHD support for disc-based systems

### ISSUE THREAD

**Issue by NTripleOne** [Swordfish90/Lemuroid#77]
The compression benefits of the CHD format are too good to ignore, and as such my entire PSX collection is stored in this format - Lemuroid does not pick any of these up when scanning for content.

I'm assuming that this is because there is no CHD support, as the same ROMs scan fine in Retroarch.

**Comment by Swordfish90** [comment]
Interesting. Apparently chd is not mentioned in the pcsx_rearmed documentation (https://docs.libretro.com/library/pcsx_rearmed/), but seems supported.

I'll add it to the list of supported formats. Since it's compressed Lemuroid won't be able to extract the serial from the image, so you'd have to put them in a folder named "psx" in order for the scanning to work.

**Comment by Swordfish90** [comment]
Could you please check the version that I just released on the beta channel and let me know if everything works as expected?

**Comment by MrChip53** [comment]
@Swordfish90 has this been resolved?

**Comment by Swordfish90** [comment]
@MrChip53 ... Yes, thank you. This landed in 1.6.0.
