### ISSUE TITLE
choppy psx audio?

### ISSUE THREAD

**Issue by rhizene** [Swordfish90/Lemuroid#917]
**Disclamer**
In order to keep this bug tracker manageable, you need to keep a few things in mind:
* Any issue not following this template will be closed as invalid
* Is the issue reproducible on RetroArch with the same core? If so, it's very likely a core issue and the upstream core repository is a better place to file it
* Is the issue already opened? Try out a search before filing one.

**Describe the bug**
psx game is playable, but audio is very choppy. 

**To Reproduce**
1. Clear app data
2. Let Lemuroid go online
3. Scan folder
4. Play any psx title

**Expected behavior**
Emulated as usual. 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Huawei Nova 2lite
 - OS: Android 8

**Additional context**
n/a

**Comment by master1274** [comment]
If the problem appeared after updating from 1.15.0 to 1.16.1, then the reason may be that the dynamic recompiler is disabled in the core settings. Although it is displayed as enabled. Or disable and enable it again by restarting the emulator. Or (best) reset all emulator settings. Because There may be problems with the settings of other cores.

**Comment by rhizene** [comment]
Fixed by toggling the dynamic recompiler on. Thanks!

**Comment by master1274** [comment]
So it needs to be closed issue.
