### ISSUE TITLE
Update local copy of Libretro Database

### ISSUE THREAD

**Issue by rwnobrega** [Swordfish90/Lemuroid#98]
[libretro-db.sqlite](../blob/master/lemuroid-metadata-libretro-db/src/main/assets/libretro-db.sqlite) seems to be outdated (7 months ago as of today). Perhaps it is a good idea to update it before each release?

**Comment by Swordfish90** [comment]
You're definitely right. Sadly the last time I tried many titles were incorrectly reported as "comment" instead of title, so I need to take a look at the rdb library written in go. I'll target this for 1.7+ (since 1.7.0 it's almost ready).

**Comment by rwnobrega** [comment]
I wrote a Python version of [libretro-sqlite-db.go](https://github.com/Swordfish90/libretro-sqlite-db) that uses `libretrodb_tool` from [RetroArch/libretro-db/](https://github.com/libretro/RetroArch/tree/master/libretro-db) instead of the rdb library written in Go. 
Apparently it gets more entries (13668 vs 13437 in psx rdb, for example).  And it is considerably faster.  Let me know if you are interested!

**Comment by Swordfish90** [comment]
Thank you! @rwnobrega that's some great news! I'm very interested in taking a look at it. It might be a good replacement to the go version I'm using right now.

**Comment by rwnobrega** [comment]
There you go: https://github.com/rwnobrega/libretro-sqlite-db

Let me know if you think it should be modified in any way --- or just throw it in the trash! :)

**Comment by Swordfish90** [comment]
I just run your script and it's blazingly fast. I just added a filter that excludes ROMs with empty names and I'll bundle the result in the next update. It seems that in these six months a lot of games were added, we went from 52k to 60k.

I'd say that given the speed and the availability of more fields (such as the additional hashes) compared to the Ludo go library I was using, this is much better.

Could you please send me this as a pull request so that I'll integrate it into the repo?

Thank you for the awesome work!

**Comment by rwnobrega** [comment]
Great!  Pull request sent. :)

**Comment by Swordfish90** [comment]
Database updated to the current trunk in #101 . Thank you again for opening the issue and providing the new script.
